Ar 137 display semesters in an accordion format
CS-458/academic-requirements pull request #23
Opened 2023-03-22 20:33 UTC by the10thWiz

# Jira Ticket

[AR-137](https://academic-cs458.atlassian.net/jira/software/projects/AR/boards/1/backlog?selectedIssue=AR-137)

# Description of Changes

Converts the semester display to use a collapsible accordion format.

# Type of Change

Feature Update: Convert existing display to a cleaner Mui format.

# How has this been tested?

- [x] SemesterList.test.tsx
  - [x] Render Semester List: Verifies basic rendering and functionality of the semester list, including drag and drop
  - [x] Only first year is visible: Checks that only the first year is expanded by default.

# Checklist
- [x] My code follows ES Lint guidelines
- [x] My solution meets all of the acceptance criteria for the user story
- [x] My code contains necessary comments and documentation
- [x] I have added tests that are useful and cover the new changes
- [x] New and existing unit tests pass locally

2023-03-22 23:49 UTC, ruudkas requested changes, later dismissed

2023-03-22 23:49 UTC, ruudkas commented on entities/four_year_plan.ts
> +  };
Can we get some comments for the new interfaces defined in this file?

2023-03-22 23:49 UTC, ruudkas commented on components/SemesterList.tsx
> +}
1.  Can we get some comments in this file?
2. I see that you are still calculating the semester credit warning, but are no longer using it? What's up with that?
3. What's with the big comment in the return?

2023-03-23 00:21 UTC, ruudkas commented
Collection of general comments (there's a lot, sorry):
1. Can we start at year 1 instead of 0?
2. This may require a group discussion, but I think that we wanted to start the user with only fall/spring semesters and then allow them to add an optional winter or summer semester. We have tasks for this in the backlog. This may require a discussion on Monday.
3. I still don't like the coloring of the accordion/semesters, but if everyone disagrees with me, then fine. Maybe switching semesters to blue and accordian to white, this might not look any better, then maybe switch the color of the accordion headers to white?
4. I mentioned this in another comment but what happened to our credit warnings. Maybe this was discussed in class and I just missed it, but it seems to be calculated then not used.
5. If it's not a pain to do, I think it would be better if the semester size when it didn't have any courses was around the same size as when it has one course in it, supplies a larger area for dropping a course. I have missed the drop mark several times while testing.
6. Along with the previous, can we have the color change of the semester when hovering back? I don't care what color, but some indication that the course is actually going to go in a semester when you release it.
7. Is it possible to maintain a manually opening of an accordian until a manually close of the accordion section? Right now if I manually open a couple years and then try to drag a course the accordion collapses, which I imagine would get pretty annoying if you were trying to view and edit your entire schedule. This seems to be caused by the opening on hover when you're dragging a course.
8. **FOUR YEAR PLANS ARE COMPLETELY BROKEN.** The entire app crashes when you select a four year plan.
9. **BOTH DUPLICATE COURSES AND WRONG SEMESTER (Fall/Spring) ARE BROKEN** There is no color change of the course and no error message being thrown.
10. There appears to be a new bug with prereqs, If I put CNIT-134 before CNIT-133 it turns red but no error message is thrown. (Using CS-Security) If I move 133 to after 134 it throws and error but moving 134 before 133 does not throw an error. 
11. **REQUIREMENTS HAS ZERO FUNCTIONALITY???** You completely removed the requirement checking from handleDrop so there is no longer any requirements updating happening.

Note for the entire team: We need better testing, there is a lot of stuff here that should be unit tested so we know that we broke previous work.

2023-03-23 18:49 UTC, ChrisVasterling commented
> Collection of general comments (there's a lot, sorry):
> 
> 1. Can we start at year 1 instead of 0?
> 2. This may require a group discussion, but I think that we wanted to start the user with only fall/spring semesters and then allow them to add an optional winter or summer semester. We have tasks for this in the backlog. This may require a discussion on Monday.
> 3. I still don't like the coloring of the accordion/semesters, but if everyone disagrees with me, then fine. Maybe switching semesters to blue and accordian to white, this might not look any better, then maybe switch the color of the accordion headers to white?
> 4. I mentioned this in another comment but what happened to our credit warnings. Maybe this was discussed in class and I just missed it, but it seems to be calculated then not used.
> 5. If it's not a pain to do, I think it would be better if the semester size when it didn't have any courses was around the same size as when it has one course in it, supplies a larger area for dropping a course. I have missed the drop mark several times while testing.
> 6. Along with the previous, can we have the color change of the semester when hovering back? I don't care what color, but some indication that the course is actually going to go in a semester when you release it.
> 7. Is it possible to maintain a manually opening of an accordian until a manually close of the accordion section? Right now if I manually open a couple years and then try to drag a course the accordion collapses, which I imagine would get pretty annoying if you were trying to view and edit your entire schedule. This seems to be caused by the opening on hover when you're dragging a course.
> 8. **FOUR YEAR PLANS ARE COMPLETELY BROKEN.** The entire app crashes when you select a four year plan.
> 9. **BOTH DUPLICATE COURSES AND WRONG SEMESTER (Fall/Spring) ARE BROKEN** There is no color change of the course and no error message being thrown.
> 10. There appears to be a new bug with prereqs, If I put CNIT-134 before CNIT-133 it turns red but no error message is thrown. (Using CS-Security) If I move 133 to after 134 it throws and error but moving 134 before 133 does not throw an error.
> 11. **REQUIREMENTS HAS ZERO FUNCTIONALITY???** You completely removed the requirement checking from handleDrop so there is no longer any requirements updating happening.
> 
> Note for the entire team: We need better testing, there is a lot of stuff here that should be unit tested so we know that we broke previous work.

I can either confirm or agree with everything Kassidy has made note of. I find the auto closing of accordions when dragging a course between semesters (point 7) particularly annoying. Also, as far as I recall, Kassidy is correct in her understanding of point 2, but this can be open for discussion if people disagree.

2023-03-23 18:56 UTC, ChrisVasterling commented on components/layout/DefaultLayout.tsx
> +        height: "100vh",
I believe this height is contributing to the additional whitespace below the header on both pages. Toggling it off in the browser dev tools seems to fix it visually (but may break something else)

2023-03-23 19:02 UTC, ChrisVasterling commented on components/layout/DefaultLayout.tsx
> +        height: "100vh",
I think this would give the desired result without the whitespace
```css
height: 100vh;
display: flex;
flex-direction: column;
```

2023-03-27 19:02 UTC, ruudkas commented
New List of Comments:

- [ ] Moving a prerequisite from in front of a course to after it does not throw an error. To recreate: add CS-145, add CS-144 before it then drag after it. I am saying it takes at least 2-3 moves of the course after CS-145 to throw an error.
- [ ] Moving CNIT-133 to be in the winter does not throw an error for being in the wrong semester but moving to spring or summer does.
- [ ] Prerequisites are not checking if the course is in winter or summer properly.
- [ ] If there are multiple instances of a course and only some of them should be in an error state, the right ones are not the only ones lit up. This could definitely fall under the bug stories we have in this sprint though.

2023-03-27 19:03 UTC, ruudkas commented
I would prefer either no color change on the low/high warning or the color to be much more opaque.

2023-03-27 23:06 UTC, ruudkas approved these changes
LGTM, I can't find any new bugs.

2023-03-28 00:00 UTC, ChrisVasterling approved these changes
look mom, we're a real app

2023-03-28 00:01 UTC, merged